# Generated by Django 5.1.1 on 2024-09-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_photos/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='problem_photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
