# Generated by Django 5.1.1 on 2024-09-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emergency_photo_alter_problem_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_problem',
            old_name='danger_level',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='ai_emergency',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='ai_problem',
            name='solution',
        ),
        migrations.AddField(
            model_name='ai_emergency',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ai_problem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='conclusion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ai_emergency',
            name='authority_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_emergency_authority_ai', to='core.authority'),
        ),
        migrations.AlterField(
            model_name='ai_emergency',
            name='danger_level',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ai_problem',
            name='authority_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_problems_authority_ai', to='core.authority'),
        ),
    ]
