# Generated by Django 5.1.1 on 2024-09-19 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_authority_specialty_remove_authority_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=1500)),
                ('reports_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='ai_emergency',
            name='authority_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_emergencies', to='core.authority'),
        ),
        migrations.AlterField(
            model_name='ai_problem',
            name='authority_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_problems', to='core.authority'),
        ),
        migrations.AlterField(
            model_name='review',
            name='related_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.problem'),
        ),
    ]
