# Generated by Django 5.1.1 on 2024-09-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='reports_id',
            new_name='review_ids',
        ),
    ]
